# 第一课


什么是PyTorch?
================

PyTorch是一个基于Python的科学计算库，它有以下特点:

- 类似于NumPy，但是它可以使用GPU
- 可以用它定义深度学习模型，可以灵活地进行深度学习模型的训练和使用

Tensors
---------------


Tensor类似与NumPy的ndarray，唯一的区别是Tensor可以在GPU上加速运算。


构造一个未初始化的5x3矩阵:

In [1]:
import torch

In [2]:
torch.empty(5,3)

tensor([[1.0469e-38, 9.1836e-39, 1.0561e-38],
        [9.4592e-39, 8.4490e-39, 1.0102e-38],
        [9.0919e-39, 1.0102e-38, 8.9082e-39],
        [8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38]])

构建一个随机初始化的矩阵:

In [3]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

构建一个全部为0，类型为long的矩阵:

也可以从一个已有的tensor构建一个tensor。这些方法会重用原来tensor的特征，例如，数据类型，除非提供新的数据。

In [6]:
x = torch.zeros(5,3)
y = torch.ones_like(x)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

得到tensor的形状:

In [7]:
y.shape

torch.Size([5, 3])

<div class="alert alert-info"><h4>注意</h4><p>``torch.Size`` 返回的是一个tuple</p></div>

Operations


有很多种tensor运算。我们先介绍加法运算。



In [9]:
x + y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

另一种着加法的写法


In [10]:
torch.add(x, y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

加法：把输出作为一个变量

In [12]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


in-place加法

In [16]:
z=torch.zeros(5,3, dtype = torch.long)
z

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

<div class="alert alert-info"><h4>注意</h4><p>任何in-place的运算都会以``_``结尾。
    举例来说：``x.copy_(y)``, ``x.t_()``, 会改变 ``x``。</p></div>

各种类似NumPy的indexing都可以在PyTorch tensor上面使用。


In [20]:
x = torch.rand(5,3)
x[1:,1:]

tensor([[0.1048, 0.4919],
        [0.8014, 0.8140],
        [0.1734, 0.4728],
        [0.6941, 0.4998]])

Resizing: 如果你希望resize/reshape一个tensor，可以使用``torch.view``：

In [2]:
import torch
x = torch.randn(4,4)
y = x.view(16)
z = x.view(8,-1)
z

tensor([[ 1.9080, -0.2536, -0.1796,  0.5646,  0.0972, -0.7150,  1.0461, -0.7265],
        [ 0.9863, -0.6148,  1.0807, -0.1457,  1.2357, -0.5884, -1.2118, -0.3474]])

如果你有一个只有一个元素的tensor，使用``.item()``方法可以把里面的value变成Python数值。

In [22]:
x = torch.randn(1)
x

tensor([1.2742])

In [23]:
x.item()

1.2742063999176025

In [8]:
z.transpose(0,1)

tensor([[ 1.9080,  0.9863],
        [-0.2536, -0.6148],
        [-0.1796,  1.0807],
        [ 0.5646, -0.1457],
        [ 0.0972,  1.2357],
        [-0.7150, -0.5884],
        [ 1.0461, -1.2118],
        [-0.7265, -0.3474]])

**更多阅读**


  各种Tensor operations, 包括transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers在
  `<https://pytorch.org/docs/torch>`.

Numpy和Tensor之间的转化
------------

在Torch Tensor和NumPy array之间相互转化非常容易。

Torch Tensor和NumPy array会共享内存，所以改变其中一项也会改变另一项。

把Torch Tensor转变成NumPy Array


In [24]:
import numpy as np

In [34]:

b = torch.ones(5)
a = b.numpy()
b[1] = 2

a

array([1., 2., 1., 1., 1.], dtype=float32)

改变numpy array里面的值。

In [51]:
b[1] = 2
b

array([1., 2., 1., 1., 1.], dtype=float32)

In [52]:
a

tensor([1., 2., 1., 1., 1.])

把NumPy ndarray转成Torch Tensor

In [54]:
import numpy as np

In [55]:
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)

[2. 2. 2. 2. 2.]


In [56]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

所有CPU上的Tensor都支持转成numpy或者从numpy转成Tensor。

CUDA Tensors
------------

使用``.to``方法，Tensor可以被移动到别的device上。



In [36]:
torch.cuda.is_available()

False

In [38]:
x = torch.rand(3,5,device=torch.device("cpu"))
y = torch.randn_like(x)
y

tensor([[ 0.8527, -0.6707,  1.3344, -0.5205,  1.5330],
        [ 0.0560,  0.6427, -1.0771,  0.3428, -1.1630],
        [ 1.6374, -1.1962,  0.4523,  0.3119,  0.2247]])

In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cuda", torch.double))
    

tensor([[ 2.9080,  0.7464,  0.8204,  1.5646],
        [ 1.0972,  0.2850,  2.0461,  0.2735],
        [ 1.9863,  0.3852,  2.0807,  0.8543],
        [ 2.2357,  0.4116, -0.2118,  0.6526]], device='cuda:0')
tensor([[ 2.9080,  0.7464,  0.8204,  1.5646],
        [ 1.0972,  0.2850,  2.0461,  0.2735],
        [ 1.9863,  0.3852,  2.0807,  0.8543],
        [ 2.2357,  0.4116, -0.2118,  0.6526]], device='cuda:0',
       dtype=torch.float64)


In [ ]:
y.to("cpu").data.numpy()
y.cpu().data.numpy()

In [ ]:
model = model.cuda()


In [39]:
y = torch.tensor([1,2,3])
y.to("cuda")